// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjwYgM8dOKy3HeIF0r5LIE1L30JAmPKp0',
    appId: '1:799730118185:android:06e200ce371dfa5efbf638',
    messagingSenderId: '799730118185',
    projectId: 'sports-network-bb94b',
    databaseURL: 'https://sports-network-bb94b-default-rtdb.firebaseio.com',
    storageBucket: 'sports-network-bb94b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXj2zndPja1po5mBKQlUTTRXA2KVeA-3k',
    appId: '1:799730118185:ios:d3b95256f8247fcffbf638',
    messagingSenderId: '799730118185',
    projectId: 'sports-network-bb94b',
    databaseURL: 'https://sports-network-bb94b-default-rtdb.firebaseio.com',
    storageBucket: 'sports-network-bb94b.appspot.com',
    iosClientId: '799730118185-1ikqaeu1dvni36ieunl3vtr6jsbn8lcp.apps.googleusercontent.com',
    iosBundleId: 'com.brilloconnetz.sportsNetwork',
  );
}
